name: "PR Analytics"

on:
  # push:
  #   branches:
  #     - main
  #     - master
  #     - test3
  schedule:
    - cron: '40 9 * * *' #UTC time
    - cron: '0 1 1 * *'
jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Get the date range of the last week"
        if: github.event.schedule == '40 9 * * 3'
        run: |
          echo "START_DATE=$(TZ=Asia/Shanghai date -d '8 days ago' +%-d/%-m/%Y)" >> $GITHUB_ENV
          echo "END_DATE=$(TZ=Asia/Shanghai date -d '1 days ago' +%-d/%-m/%Y)" >> $GITHUB_ENV
          echo "CRON_PERIOD=week" >> $GITHUB_ENV

      - name: "Get the date range of the last month"
        if: github.event.schedule == '0 1 1 * *'
        run: |
          echo "START_DATE=$(TZ=Asia/Shanghai date -d "last month" +1/%-m/%Y)" >> $GITHUB_ENV
          echo "END_DATE=$(TZ=Asia/Shanghai date -d '1 days ago' +%-d/%-m/%Y)" >> $GITHUB_ENV
          echo "CRON_PERIOD=month" >> $GITHUB_ENV

      - name: "Get Date"
        run: |
          echo "START_DATE=$(TZ=Asia/Shanghai date -d '30 days ago' +%-d/%-m/%Y)" >> $GITHUB_ENV
          echo "END_DATE=$(TZ=Asia/Shanghai date +%-d/%-m/%Y)" >> $GITHUB_ENV

      - name: "Run script for analytics"
        uses: AlexSim93/pull-request-analytics-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.PR_TOKEN }} # In the case of a personal access token, it needs to be added to the repository's secrets and used in this field.
          GITHUB_REPO_FOR_ISSUE: pr-analytics-demo
          GITHUB_OWNER_FOR_ISSUE: zenkzen-org
          GITHUB_OWNERS_REPOS: zenkzen-org/pr-analytics-demo,zenkzen-org/runner-test
          TIMEZONE: Asia/Shanghai
          REPORT_DATE_START: ${{ env.START_DATE }}
          REPORT_DATE_END: ${{ env.END_DATE }}