name: "PR Analytics"
on:
#   # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ main, master ]

  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(d/MM/yyyy)"
      report_date_end:
        description: "Report date end(d/MM/yyyy)"
jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: Get Date
        run: |
          echo "START_DATE=$(TZ=Asia/Shanghai date -d '30 days ago' +%d/%m/%y)" >> $GITHUB_ENV
          echo "END_DATE=$(TZ=Asia/Shanghai date '+%d/%m/%y')" >> $GITHUB_ENV

      - name: "Run script for analytics"
        uses: AlexSim93/pull-request-analytics-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.PR_TOKEN }} # In the case of a personal access token, it needs to be added to the repository's secrets and used in this field.
          GITHUB_REPO_FOR_ISSUE: pr-analytics-demo
          GITHUB_OWNER_FOR_ISSUE: zenkzen-org
          GITHUB_OWNERS_REPOS: zenkzen-org/runner-test
          # CORE_HOURS_START: "00:00"
          # CORE_HOURS_END: "23:59"
          TIMEZONE: "Asia/Shanghai"
          # REPORT_DATE_START: ${{ env.START_DATE }}
          # REPORT_DATE_START: 20/7/2024
          # REPORT_DATE_END: ${{ env.END_DATE }}
          # REPORT_DATE_END: 27/03/25
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}